name: Release

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '22.14.0'
          
      - name: Install dependencies
        run: npm ci
        
      - name: Build project
        run: npm run build:release
        
      - name: Create archives
        run: |
          cd dist
          zip -r ../release.zip .
          tar -czf ../release.tar.gz .
          cd ..
          
      - name: Upload ZIP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-zip
          path: ./release.zip
          
      - name: Upload TAR Artifact
        uses: actions/upload-artifact@v4
        with:
          name: release-tar
          path: ./release.tar.gz